INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES(30, 'Maria', 'Green');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES(28, 'Mary', 'Poppins');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES(19, 'Tony', 'Danska');