INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES(30, 'Maria', 'Green');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES(28, 'Mary', 'Poppins');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES(19, 'Tony', 'Danska');

INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES('Tomato', 4);
INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES('Milk', 3);
INSERT INTO PRODUCT_ENTITIES (PRODUCT_NAME, PRICE)
VALUES('Cheese', 5);